[theme]
base = "dark"
primaryColor = "#FF5500"
backgroundColor = "#3f3b3b"
secondaryBackgroundColor = "#FF5500"
textColor = "#f2e1e1"
font = "serif"

[browser]
gatherUsageStats = false

[logger]
level = "info"